
# my config
[line_break]
disabled = true

# Dracula theming
[character]
error_symbol = "[Î»](bold #ff5555)"
success_symbol = "[Î»](bold #50fa7b)"

[cmd_duration]
style = "bold #FFFF80"
format = '[âŒ› $duration]($style) '

[git_status]
style = "bold #ff5555"
format = '([\[$all_status$ahead_behind\]]($style) )'


# Nerd fonts default
[aws]
symbol = "îŒ½  "
format = '[$symbol($profile)(\($region\))(\[$duration\])]($style)'
# Dracula
style = "bold #ffb86c"

[bun]
format = '[$symbol($version)]($style)'

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "
format = '[$symbol($version(-$name))]($style)'

[cmake]
format = '[$symbol($version)]($style)'

[cobol]
format = '[$symbol($version)]($style)'

[conda]
symbol = "ï„Œ "
format = '[$symbol$environment]($style)'

[crystal]
format = '[$symbol($version)]($style)'

[daml]
format = '[$symbol($version)]($style)'

[dart]
symbol = "î˜ "
format = '[$symbol($version)]($style)'

[deno]
format = '[$symbol($version)]($style)'

[directory]
read_only = " ó°Œ¾"
# Dracula
style = "bold #50fa7b"

[docker_context]
symbol = "ïŒˆ "
format = '[$symbol$context]($style)'

[dotnet]
format = '[$symbol($version)(ğŸ¯ $tfm)]($style)'

[elixir]
symbol = "î‰µ "
format = '[$symbol($version \(OTP $otp_version\))]($style)'

[elm]
symbol = "î˜¬ "
format = '[$symbol$context]($style)'

[erlang]
format = '[$symbol$context]($style)'

[fennel]
format = '[$symbol$context]($style)'

[fossil_branch]
symbol = "ï˜ "
format = '[$symbol$branch]($style) '

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
symbol = "ï˜ "
# Dracula
style = "bold #FF80BF"
format = '[$symbol$branch]($style) '

[golang]
symbol = "î˜§ "
format = '[$symbol($version)]($style)'

[gradle]
format = '[$symbol($version)]($style)'

[guix_shell]
symbol = "ïŒ¥ "
format = '[$symbol]($style) '

[haskell]
symbol = "î· "
format = '[$symbol($version)]($style)'

[haxe]
symbol = "î™¦ "
format = '[$symbol($version)]($style)'

[helm]
format = '[$symbol($version)]($style)'

[hg_branch]
symbol = "ï˜ "
format = '[$symbol$branch]($style) '

[hostname]
ssh_symbol = "î¬ "
# Dracula
style = "bold #bd93f9"

[java]
symbol = "î‰– "
format = '[$symbol($version)]($style)'

[julia]
symbol = "î˜¤ "
format = '[$symbol($version)]($style)'

[kotlin]
format = '[$symbol($version)]($style)'

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style)'

[lua]
symbol = "î˜  "
format = '[$symbol($version)]($style)'

[memory_usage]
symbol = "ó°› "
format = '$symbol[$ram( | $swap)]($style) '

[meson]
symbol = "ó°”· "
format = '[$symbol$project]($style) '

[nim]
symbol = "ó°†¥ "
format = '[$symbol($version)]($style)'

[nix_shell]
symbol = "ïŒ“ "
format = '[$symbol$state( \($name\))]($style)'

[nodejs]
symbol = "îœ˜ "
format = '[$symbol($version)]($style)'

[ocaml]
format = '[$symbol($version)(\($switch_indicator$switch_name\))]($style)'

[opa]
format = '[$symbol($version)]($style)'

[openstack]
format = '[$symbol$cloud(\($project\))]($style)'

[os]
format = '[$symbol]($style)'

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[package]
symbol = "ó°— "
format = '[$symbol$version]($style)'

[perl]
format = '[$symbol($version)]($style)'

[php]
format = '[$symbol($version)]($style)'

[pijul_channel]
symbol = "ï˜ "
format = '[$symbol$channel]($style) '

[pulumi]
format = '[$symbol$stack]($style) '

[purescript]
format = '[$symbol($version)]($style)'

[python]
symbol = "îˆµ "
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[raku]
format = '[$symbol($version-$vm_version)]($style)'

[rlang]
symbol = "ó°Ÿ” "
format = '[$symbol($version)]($style)'

[red]
format = '[$symbol($version)]($style)'

[ruby]
symbol = "î‘ "
format = '[$symbol($version)]($style)'

[rust]
symbol = "î¨ "
format = '[$symbol($version)]($style)'

[scala]
symbol = "îœ· "
format = '[$symbol($version)]($style)'

[spack]
format = '[$symbol$environment]($style)'

[sudo]
disabled = false

[swift]
format = '[$symbol($version)]($style)'

[terraform]
format = '[$symbol$workspace]($style)'

[time]
format = '[$time]($style) '

[username]
format = "[$user]($style) "
style_user = "bold #80FFEA"

[vagrant]
format = '[$symbol($version)]($style)'

[vlang]
format = '[$symbol($version)]($style)'

[zig]
format = '[$symbol($version)]($style)'

[solidity]
format = '[$symbol($version)]($style)'
